apiVersion: v1
kind: ConfigMap
metadata:
  name: laman-config
  namespace: laman-dev
data:
  # База данных
  DB_HOST: "postgres"        # имя Service postgres — Kubernetes сам резолвит
  DB_PORT: "5432"
  DB_SSLMODE: "disable"

  # Сервер
  SERVER_PORT: "8080"
  SERVER_HOST: "0.0.0.0"
  PUBLIC_URL: "http://localhost:8080"

  # Redis — имя Service redis
  REDIS_URL: "redis://redis:6379"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # Jaeger — имя Service jaeger
  JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"

  # CORS
  CORS_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
