stages:
  - lint
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/khadzhiev404/laman-backend
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

lint:
  stage: lint
  tags:
    - local
  script:
    - cd Backend
    - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:latest golangci-lint run ./...
  only:
    - main
    - merge_requests

build:
  stage: build
  tags:
    - local
  script:
    - cd Backend
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  only:
    - main

deploy_staging:
  stage: deploy
  tags:
    - local
  script:
    - kubectl set image deployment/laman-api laman-api=$IMAGE_NAME:$IMAGE_TAG -n laman-dev
    - kubectl rollout status deployment/laman-api -n laman-dev
  only:
    - main

deploy_prod:
  stage: deploy
  tags:
    - local
  script:
    - kubectl set image deployment/laman-api laman-api=$IMAGE_NAME:$IMAGE_TAG -n laman-prod
    - kubectl rollout status deployment/laman-api -n laman-prod
  when: manual
  only:
    - main