apiVersion: apps/v1
kind: Deployment
metadata:
  name: laman-api
  namespace: laman-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laman-api
  template:
    metadata:
      labels:
        app: laman-api
    spec:
      containers:
        - name: laman-api
          image: laman-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: laman-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: db-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: db-name
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: jwt-secret
            - name: SMS_RU_KEY
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: sms-ru-key
            - name: SMSRU_API_KEY
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: sms-ru-key
            - name: TG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: tg-bot-token
            - name: TG_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: tg-chat-id
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: admin-user
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laman-secrets
                  key: admin-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: uploads
              mountPath: /root/uploads
      volumes:
        - name: uploads
          emptyDir: {}
