apiVersion: v1
kind: Service
metadata:
  name: postgres        # именно это имя резолвится как hostname внутри кластера
  namespace: laman-dev
spec:
  type: ClusterIP       # только внутри кластера — снаружи PostgreSQL не нужен
  selector:
    app: postgres       # направляй трафик на поды с этим лейблом
  ports:
    - port: 5432
      targetPort: 5432
